=== IRT-Open-Source/imsced/requirements/requirements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="requirements">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="requirement"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="collection">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="areas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="area"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="usecases">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="usecase"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="requirementStatuses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="requirementStatus"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="implementationStatuses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="implementationStatus"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="priorities">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="priority"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="releases">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" ref="release"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="requirements"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="area">
        <xs:complexType>
            <xs:choice>
                <xs:element name="IDREF" type="xs:IDREF"/>
                <xs:sequence>
                    <xs:element name="ID" type="xs:ID"/>
                    <xs:element ref="title"/>
                    <xs:element ref="description"/>
                </xs:sequence>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="requirement">
        <xs:complexType>
            <xs:choice>
                <xs:element name="IDREF" type="xs:IDREF"/>
                <xs:sequence>
                    <xs:element name="ID" type="xs:ID"/>
                    <xs:element ref="title"/>
                    <xs:element ref="description"/>
                    <xs:element maxOccurs="unbounded" name="requirementArea">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="area"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element maxOccurs="unbounded" name="requirementUsecase">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="usecase"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="created" type="xs:date"/>
                    <xs:element name="reviewStatus">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="requirementStatus"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="requirementPriority">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element minOccurs="0" ref="priority"> </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="link" type="xs:anyURI" minOccurs="0"/>
                    <xs:element minOccurs="0" name="requirementImplementationStatus">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element minOccurs="0" ref="implementationStatus"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="info" minOccurs="0"/>
                    <xs:element minOccurs="0" name="requirementRelease">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="release"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="title"/>
    <xs:element name="description"/>
    <xs:element name="usecase">
        <xs:complexType>
            <xs:choice>
                <xs:element name="IDREF" type="xs:IDREF"/>
                <xs:sequence>
                    <xs:element name="ID" type="xs:ID"/>
                    <xs:element ref="title"/>
                    <xs:element ref="description"/>
                </xs:sequence>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="requirementStatus">
        <xs:complexType>
            <xs:choice>
                <xs:element name="IDREF" type="xs:IDREF"/>
                <xs:sequence>
                    <xs:element name="ID" type="xs:ID"/>
                    <xs:element ref="title"/>
                    <xs:element ref="description" minOccurs="0"/>
                </xs:sequence>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="implementationStatus">
        <xs:complexType>
            <xs:choice>
                <xs:element name="IDREF" type="xs:IDREF"/>
                <xs:sequence>
                    <xs:element name="ID" type="xs:ID"/>
                    <xs:element ref="title"/>
                    <xs:element ref="description" minOccurs="0"/>
                </xs:sequence>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="priority">
        <xs:complexType>
            <xs:choice>
                <xs:element name="IDREF" type="xs:IDREF"/>
                <xs:sequence>
                    <xs:element name="ID" type="xs:ID"/>
                    <xs:element ref="title"/>
                    <xs:element ref="description" minOccurs="0"/>
                </xs:sequence>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="release">
        <xs:complexType>
            <xs:choice>
                <xs:element name="IDREF" type="xs:IDREF"/>
                <xs:sequence>
                    <xs:element name="ID" type="xs:ID"/>
                    <xs:element ref="title"/>
                    <xs:element ref="description" minOccurs="0"/>
                    <xs:element name="releaseDate" type="xs:date"/>
                </xs:sequence>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IRT-Open-Source/imsced/requirements/req.xml
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="requirements.xsd">
  <areas>
    <area>
      <ID>area-id-none</ID>
      <title>tbd</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-UTBearbeitung</ID>
      <title>UT Bearbeitung</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-Segmentierung</ID>
      <title>Segmentierung</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-Playback</ID>
      <title>Playback</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-Synchronisation</ID>
      <title>Synchronisation</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-Konfiguration</ID>
      <title>Konfiguration</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-VideoFormate</ID>
      <title>Video Formate</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-UTImportFormate</ID>
      <title>UT Import Formate</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-UTExportFormate</ID>
      <title>UT Export Formate</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-QC</ID>
      <title>QC</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-standzeit</ID>
      <title>Standzeit</title>
      <description>Alle Features die mit Anforderungen für die Standzeit zusammenhängen</description>
    </area>
    <area>
      <ID>area-id-lesgegeschwindigkeit</ID>
      <title>Lesegeschwindigkeit</title>
      <description>Features die in Zusammenhang mit der Lesegeschwindigkeit stehen.</description>
    </area>
    <area>
      <ID>area-id-experimental</ID>
      <title>Experimental</title>
      <description>Features, die noch nicht fertig implementiert sind, aber dennoch bereits releast werden, insbesondere um Feedback zu bekommen.</description>
    </area>
    <area>
      <ID>area-id-zeilen</ID>
      <title>Zeilen</title>
      <description>Anforderungen, die mit Untertitelzeilen zusammehängen.</description>
    </area>
    <area>
      <ID>area-id-fliesstext</ID>
      <title>Fließtext</title>
      <description>tbd</description>
    </area>
    <area>
      <ID>area-id-shortcuts</ID>
      <title>Shortcuts</title>
      <description>tbd</description>
    </area>
  </areas>
  <usecases>
    <usecase>
      <ID>usecase-id-none</ID>
      <title>tbd</title>
      <description>tbd</description>
    </usecase>
    <usecase>
      <ID>usecase-id-NachbearbeitungSTT</ID>
      <title>Nachbearbeitung STT</title>
      <description>tbd</description>
    </usecase>
    <usecase>
      <ID>usecase-id-VerarbeitungvonSkripten</ID>
      <title>Verarbeitung von Skripten</title>
      <description>tbd</description>
    </usecase>
    <usecase>
      <ID>usecase-id-Neuerstellung</ID>
      <title>Neuerstellung</title>
      <description>tbd</description>
    </usecase>
    <usecase>
      <ID>usecase-id-AnnotationvonUT</ID>
      <title>Annotation von UT</title>
      <description>tbd</description>
    </usecase>
    <usecase>
      <ID>usecase-id-KreativeUTundNutzungimForschungsumfeld</ID>
      <title>Kreative UT und Nutzung im Forschungsumfeld</title>
      <description>tbd</description>
    </usecase>
    <usecase>
      <ID>usecase-id-SocialMediaUT</ID>
      <title>Social Media UT</title>
      <description>tbd</description>
    </usecase>
    <usecase>
      <ID>usecase-id-generic</ID>
      <title>Allgemeiner Gebrauch eines Untertiteleditors</title>
      <description>Anforderungen die generell für alle btw. die Mehrzahl der Anwendungsfälle zutreffen.</description>
    </usecase>
  </usecases>
  <requirementStatuses>
    <requirementStatus>
      <ID>requirementStatus-id-open</ID>
      <title>open</title>
      <description>tbd</description>
    </requirementStatus>
    <requirementStatus>
      <ID>requirementStatus-id-inDiscussion</ID>
      <title>inDiscussion</title>
      <description>tbd</description>
    </requirementStatus>
    <requirementStatus>
      <ID>requirementStatus-id-accepted</ID>
      <title>accepted</title>
      <description>tbd</description>
    </requirementStatus>
    <requirementStatus>
      <ID>requirementStatus-id-workingOn</ID>
      <title>workingOn</title>
      <description>tbd</description>
    </requirementStatus>
    <requirementStatus>
      <ID>requirementStatus-id-resolved</ID>
      <title>resolved</title>
      <description>tbd</description>
    </requirementStatus>
    <requirementStatus>
      <ID>requirementStatus-id-feedback</ID>
      <title>feedback</title>
      <description>tbd</description>
    </requirementStatus>
  </requirementStatuses>
  <implementationStatuses>
    <implementationStatus>
      <ID>implementationstatus-id-outstanding</ID>
      <title>outstanding</title>
      <description>tbd</description>
    </implementationStatus>
    <implementationStatus>
      <ID>implementationstatus-id-waitingReview</ID>
      <title>waitingReview</title>
      <description>tbd</description>
    </implementationStatus>
    <implementationStatus>
      <ID>implementationstatus-id-underReview</ID>
      <title>underReview</title>
      <description>tbd</description>
    </implementationStatus>
    <implementationStatus>
      <ID>implementationstatus-id-reviewed</ID>
      <title>reviewed</title>
      <description>tbd</description>
    </implementationStatus>
    <implementationStatus>
      <ID>implementationstatus-id-accepted</ID>
      <title>accepted</title>
      <description>tbd</description>
    </implementationStatus>
    <implementationStatus>
      <ID>implementationstatus-id-rejected</ID>
      <title>rejected</title>
      <description>tbd</description>
    </implementationStatus>
  </implementationStatuses>
  <priorities>
    <priority>
      <ID>priority-id-Must</ID>
      <title>Must</title>
      <description>tbd</description>
    </priority>
    <priority>
      <ID>priority-id-Should</ID>
      <title>Should</title>
      <description>tbd</description>
    </priority>
    <priority>
      <ID>priority-id-Could</ID>
      <title>Could</title>
      <description>tbd</description>
    </priority>
    <priority>
      <ID>priority-id-Wont</ID>
      <title>Wont</title>
      <description>tbd</description>
    </priority>
  </priorities>
  <releases>
    <release>
      <ID>release-id-none</ID>
      <title>none</title>
      <description>Not planned yet</description>
      <releaseDate>1970-01-01</releaseDate>
    </release>
    <release>
      <ID>release-id-antman</ID>
      <title>Ant Man</title>
      <description>tbd</description>
      <releaseDate>2020-05-15</releaseDate>
    </release>
    <release>
      <ID>release-id-quicksilver</ID>
      <title>Quicksilver</title>
      <description>tbd</description>
      <releaseDate>2020-05-29</releaseDate>
    </release>
    <release>
      <ID>release-id-blackpanther</ID>
      <title>Black Panther</title>
      <description>tbd</description>
      <releaseDate>2020-06-12</releaseDate>
    </release>
  </releases>
  <requirements>
    <requirement>
      <ID>req-id-EinfügenvonTexten</ID>
      <title>Einfügen von Texten</title>
      <description>Redaktionelle Texte müssen in den Editor zur Weiterverarbeitung eingefügt werden
        können.</description>
      <requirementArea>
        <area>
          <IDREF>area-id-UTBearbeitung</IDREF>
        </area>
      </requirementArea>
      <requirementUsecase>
        <usecase>
          <IDREF>usecase-id-VerarbeitungvonSkripten</IDREF>
        </usecase>
      </requirementUsecase>
      <created>2020-04-06</created>
      <reviewStatus>
        <requirementStatus>
          <IDREF>requirementStatus-id-open</IDREF>
        </requirementStatus>
      </reviewStatus>
      <requirementPriority>
        <priority>
          <IDREF>priority-id-Must</IDREF>
        </priority>
      </requirementPriority>
      <requirementImplementationStatus>
        <implementationStatus>
          <IDREF>implementationstatus-id-outstanding</IDREF>
        </implementationStatus>
      </requirementImplementationStatus>
      <requirementRelease>
        <release>
          <IDREF>release-id-none</IDREF>
        </release>
      </requirementRelease>
    </requirement>
    <requirement>
      <ID>req-id-HinzufügenvonUntertiteln</ID>
      <title>Hinzufügen von Untertitel Blöcken</title>
      <description>Hinzufügen von einzelnen Untertitel Blöcken an beliebiger Stelle. Ein UT Block muss als  ERSTER UT Block, VOR einem und NACH einem bereits bestehenden UT Block  hinzugfügt werden können.  Beim Hinzufügen eines neuen UT Blocks wird gleichzeitg eine leere Zeile angelegt.  Option a): Beim Hinzufügen eines neuen UT Blocks wird kein TC-IN und kein TC-OUT gesetzt. Nur sinnvoll, wenn nachträchglich TC-IN und TC-OUT gesetzt werden kann.  Option b): Beim Hinzufügen eines neuen UT Blocks wird automatisch ein TC-IN und ein TC-OUT gesetzt. Nur möglich wenn bestehender UT-Block TC-IN und TC-OUT aufweist. Nach einem bestehenden UT Block: TC-IN-NEU = TC-OUT-ALT + minimaler Abstand (Framegap), TC-OUT-NEU = TC-IN-NEU + minimale Standzeit Vor einem bestehenden UT Block:  TC-OUT-NEU = TC-IN-ALT - minimaler Abstand (Framegap), TC-IN-NEU = TC-OUT-NEU - minimale Standzeit Als ertser UT Block: Sonderfall, da keine TC-IN und TC-OUT Angaben bestehender UT Blöcke vorliegen. TC-IN-NEU = 00:00:00:00, TC-OUT-NEU = TC-IN-NEU + minimale Standzeit Ob Option a) oder  Option b) angewedet wird, muss in den Einsetllungen konfiguriert werden können.</description>
      <requirementArea>
        <area>
          <IDREF>area-id-UTBearbeitung</IDREF>
        </area>
      </requirementArea>
      <requirementUsecase>
        <usecase>
          <IDREF>usecase-id-NachbearbeitungSTT</IDREF>
        </usecase>
      </requirementUsecase>
